using Microsoft.EntityFrameworkCore.Migrations;

namespace DiscoverMoldova.Infrastructure.Migrations
{
    public partial class SeedDataForLocationsTable : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                table: "Locations",
                columns: new[] { "Id", "Name", "DistrictId"},
                values: new object[,]
                {
                    { 1, "Chișinău", 10 },
                    { 2, "Codru", 10 },
                    { 3, "Cricova", 10 },
                    { 4, "Durlești", 10 },
                    { 5, "Sîngera", 10 },
                    { 6, "Vadul Lui Vodă", 10 },
                    { 7, "Vatra", 10 },
                    { 8, "Băcioi", 10 },
                    { 9, "Bîc", 10 },
                    { 10, "Brăila", 10 },
                    { 11, "Bubuieci", 10 },
                    { 12, "Budești", 10 },
                    { 13, "Buneți", 10 },
                    { 14, "Ceroborta", 10 },
                    { 15, "Cheltuitori", 10 },
                    { 16, "Ciorescu", 10 },
                    { 17, "Colonița", 10 },
                    { 18, "Condrița", 10 },
                    { 19, "Cruzești", 10 },
                    { 20, "Dobrogea", 10 },
                    { 21, "Dumbrava", 10 },
                    { 22, "Făuresti", 10 },
                    { 23, "Frumușica", 10 },
                    { 24, "Ghidighici", 10 },
                    { 25, "Goian", 10 },
                    { 26, "Goianul Nou", 10 },
                    { 27, "Grătiești", 10 },
                    { 28, "Hulboaca", 10 },
                    { 29, "Humulești", 10 },
                    { 30, "Revaca", 10 },
                    { 31, "Stăuceni", 10 },
                    { 32, "Străisteni", 10 },
                    { 33, "Tohatin", 10 },
                    { 34, "Trușeni", 10 },
                    { 35, "Văduleni", 10 },
                    { 36, "Bălți", 3 },
                    { 37, "Elizaveta", 3 },
                    { 38, "Sadovoe", 3 },
                    { 39, "Ceadîr-Lunga", 11 },
                    { 40, "Comrat", 11 },
                    { 41, "or. Vulcănești", 11 },
                    { 42, "Alexeevca", 11 },
                    { 43, "Avdarma", 11 },
                    { 44, "Baurci", 11 },
                    { 45, "Beșalma", 11 },
                    { 46, "Beșghioz", 11 },
                    { 47, "Bugeac", 11 },
                    { 48, "Carbalia", 11 },
                    { 49, "Cazaclia", 11 },
                    { 50, "Chioselia Rusă", 11 },
                    { 51, "Chiriet-Lunga", 11 },
                    { 52, "Chirsova", 11 },
                    { 53, "Cioc-Maidan", 11 },
                    { 54, "Cismichioi", 11 },
                    { 55, "Congaz", 11 },
                    { 56, "Congazcicul de Jos", 11 },
                    { 57, "Congazcicul de Sus", 11 },
                    { 58, "Copceac", 11 },
                    { 59, "Cotovscoe", 11 },
                    { 60, "Dezghingea", 11 },
                    { 61, "Dudulești", 11 },
                    { 62, "Etulia", 11 },
                    { 63, "Etulia Nouă", 11 },
                    { 64, "Ferapontievca", 11 },
                    { 65, "Gaidar", 11 },
                    { 66, "Joltai", 11 },
                    { 67, "Svetlîi", 11 },
                    { 68, "Tomai", 11 },
                    { 69, "s. Vulcănești", 11 },
                    { 70, "Camenca", 36 },
                    { 71, "Crasnoe", 36 },
                    { 72, "Dnestrovsc", 36 },
                    { 73, "Dubăsari", 36 },
                    { 74, "Grigoriopol", 36 },
                    { 75, "Maiac", 36 },
                    { 76, "Rîbnița", 36 },
                    { 77, "Slobozia", 36 },
                    { 78, "Tiraspol", 36 },
                    { 79, "Tiraspolul Nou", 36 },
                    { 80, "Afansievca", 36 },
                    { 81, "Alexandrovca", 36 },
                    { 82, "Alexandrovca Nouă", 36 },
                    { 83, "Andreevca", 36 },
                    { 84, "Andriașevca Nouă", 36 },
                    { 85, "Andriașevca Veche", 36 },
                    { 86, "Basarabca", 36 },
                    { 87, "Beloci", 36 },
                    { 88, "Bîcioc", 36 },
                    { 89, "Blijnii Hutor", 36 },
                    { 90, "Bodeni", 36 },
                    { 91, "Bosca", 36 },
                    { 92, "Brosteni", 36 },
                    { 93, "Bruslachi", 36 },
                    { 94, "Buschi", 36 },
                    { 95, "Butor", 36 },
                    { 96, "Butuceni", 36 },
                    { 97, "Calinovca", 36 },
                    { 98, "Caragaș", 36 },
                    { 99, "Carmanova", 36 },
                    { 100, "Caterinovca", 36 },
                    { 101, "Cernița", 36 },
                    { 102, "Chirov", 36 },
                    { 103, "Cioburciu", 36 },
                    { 104, "Cobasna", 36 },
                    { 105, "Coicova", 36 },
                    { 106, "Colosova", 36 },
                    { 107, "Comisarovca Nouă", 36 },
                    { 108, "Constantinovca", 36 },
                    { 109, "Corotna", 36 },
                    { 110, "Coșnița Nouă", 36 },
                    { 111, "Cotovca", 36 },
                    { 112, "Crasnaia Besarabia", 36 },
                    { 113, "Crasnaia Gorca", 36 },
                    { 114, "Crasnencoe", 36 },
                    { 115, "Crasnîi Octeabri", 36 },
                    { 116, "Crasnîi Vinogradari", 36 },
                    { 117, "Crasnoe", 36 },
                    { 118, "Crasnogorca", 36 },
                    { 119, "Cuzmin", 36 },
                    { 120, "Delacău", 36 },
                    { 121, "Dimitrova", 36 },
                    { 122, "Doibani 1", 36 },
                    { 123, "Doibani 2", 36 },
                    { 124, "Dubău", 36 },
                    { 125, "Dzerjinscoe", 36 },
                    { 126, "Fedoseevca", 36 },
                    { 127, "Frunză", 36 },
                    { 128, "Frunzăuca", 36 },
                    { 129, "Gherșunovca", 36 },
                    { 130, "Ghidirim", 36 },
                    { 131, "Goian", 36 },
                    { 132, "Goianul Nou", 36 },
                    { 133, "Haraba", 36 },
                    { 134, "Harmațca", 36 },
                    { 135, "Hîrjău", 36 },
                    { 136, "Hîrtop", 36 },
                    { 137, "Hlinaia", 36 },
                    { 138, "Hristovaia", 36 },
                    { 139, "Hrușca", 36 },
                    { 140, "Iagorlîc", 36 },
                    { 141, "Iantarnoe", 36 },
                    { 142, "India", 36 },
                    { 143, "Ivanovca", 36 },
                    { 144, "Jura", 36 },
                    { 145, "Lenin", 36 },
                    { 146, "Lîsaia Gora", 36 },
                    { 147, "Lunga", 36 },
                    { 148, "Lunga Nouă", 36 },
                    { 149, "Mălăiești", 36 },
                    { 150, "Marian", 36 },
                    { 151, "Mihailovca ", 36 },
                    { 152, "Mihailovca Nouă", 36 },
                    { 153, "Mocearovca", 36 },
                    { 154, "Mocra", 36 },
                    { 155, "Mocreachi", 36 },
                    { 156, "Molochișul Mare", 36 },
                    { 157, "Molochișul Mic", 36 },
                    { 158, "Nezavertailovca", 36 },
                    { 159, "Nicolscoe", 36 },
                    { 160, "Novaia Jizni", 36 },
                    { 161, "Novocotovsc", 36 },
                    { 162, "Novosavițcaia", 36 },
                    { 163, "Novovladimirovca", 36 },
                    { 164, "Ocnița", 36 },
                    { 165, "Ofatinți", 36 },
                    { 166, "Parcani", 36 },
                    { 167, "Pervomaisc", 36 },
                    { 168, "Pîcalova", 36 },
                    { 169, "Plopi", 36 },
                    { 170, "Pobeda", 36 },
                    { 171, "Podoima", 36 },
                    { 172, "Podoimița", 36 },
                    { 173, "Pohrebea Nouă", 36 },
                    { 174, "Popencu", 36 },
                    { 175, "Prioziornoe", 36 },
                    { 176, "Rașcov", 36 },
                    { 177, "Roghi", 36 },
                    { 178, "Rotari", 36 },
                    { 179, "Sadchi", 36 },
                    { 180, "Sărăței", 36 },
                    { 181, "Șevcenco", 36 },
                    { 182, "Severinovca", 36 },
                    { 183, "Șipca", 36 },
                    { 184, "Slobozia-Rașcov", 36 },
                    { 185, "Șmalena", 36 },
                    { 186, "Socolovca", 36 },
                    { 187, "Solnecinoe", 36 },
                    { 188, "Sovietscoe", 36 },
                    { 189, "Speia", 36 },
                    { 190, "Stanislavca", 36 },
                    { 191, "Stroiești", 36 },
                    { 192, "Sucleia", 36 },
                    { 193, "Suhaia Rîbnița", 36 },
                    { 194, "Tașlîc", 36 },
                    { 195, "Teiu", 36 },
                    { 196, "Tibuleuca", 36 },
                    { 197, "Tîrnauca", 36 },
                    { 198, "Tocmagiu", 36 },
                    { 199, "Uiutnoe", 36 },
                    { 200, "Ulmu", 36 },
                    { 201, "Ulmul Mic", 36 },
                    { 202, "Vadul Turcului", 36 },
                    { 203, "Valea Adîncă", 36 },
                    { 204, "Vărăncău", 36 },
                    { 205, "Vasilievca", 36 },
                    { 206, "Vesioloe", 36 },
                    { 207, "Vinogradnoe", 36 },
                    { 208, "Vladimirovca", 36 },
                    { 209, "Voitovca", 36 },
                    { 210, "Zaporojeț", 36 },
                    { 211, "Zăzuleni", 36 },
                    { 212, "Bender", 4 },
                    { 213, "Proteagailovca", 4 },
                    { 214, "Anenii Noi", 1 },
                    { 215, "Albinița", 1 },
                    { 216, "Balmaz", 1 },
                    { 217, "Batîc", 1 },
                    { 218, "Beriozchi", 1 },
                    { 219, "Botnărești", 1 },
                    { 220, "Botnăreștii noi", 1 },
                    { 221, "Bulboaca", 1 },
                    { 222, "Calfa", 1 },
                    { 223, "Calfa Nouă", 1 },
                    { 224, "Chetrosu", 1 },
                    { 225, "Chirca", 1 },
                    { 226, "Ciobanovca", 1 },
                    { 227, "Cobusca Nouă", 1 },
                    { 228, "Cobusca Veche", 1 },
                    { 229, "Crețoaia", 1 },
                    { 230, "Delacău", 1 },
                    { 231, "Floreni", 1 },
                    { 232, "Florești", 1 },
                    { 233, "Geamăna", 1 },
                    { 234, "Gura Bîcului", 1 },
                    { 235, "Hîrbovăț", 1 },
                    { 236, "Hîrbovățul Nou", 1 },
                    { 237, "Larga", 1 },
                    { 238, "Maximovca", 1 },
                    { 239, "Mereni", 1 },
                    { 240, "Merenii Noi", 1 },
                    { 241, "Mirnoe", 1 },
                    { 242, "Nicolaevca", 1 },
                    { 243, "Ochiul Roș", 1 },
                    { 244, "Picus", 1 },
                    { 245, "Puhăceni", 1 },
                    { 246, "Roșcani", 1 },
                    { 247, "Ruseni", 1 },
                    { 248, "Salcia", 1 },
                    { 249, "Șerpeni", 1 },
                    { 250, "Socoleni", 1 },
                    { 251, "Speia", 1 },
                    { 252, "Telița", 1 },
                    { 253, "Telița Nouă", 1 },
                    { 254, "Țînțăreni", 1 },
                    { 255, "Todirești", 1 },
                    { 256, "Troița Nouă", 1 },
                    { 257, "Varnița", 1 },
                    { 258, "Zolotievca", 1 },
                    { 259, "Basarabeasca", 2 },
                    { 260, "Abaclia", 2 },
                    { 261, "Bașcalia", 2 },
                    { 262, "Bogdanovca", 2 },
                    { 263, "Carabetovca", 2 },
                    { 264, "Carabiber", 2 },
                    { 265, "Iordanovca", 2 },
                    { 266, "Iserlia", 2 },
                    { 267, "Ivanovca", 2 },
                    { 268, "Sadaclia", 2 },
                    { 269, "Briceni", 5 },
                    { 270, "Lipcani", 5 },
                    { 271, "Balasinești", 5 },
                    { 272, "Bălcăuți", 5 },
                    { 273, "Beleavinți", 5 },
                    { 274, "Berlinți", 5 },
                    { 275, "Bezeda", 5 },
                    { 276, "Bocicăuți", 5 },
                    { 277, "Bogdănești", 5 },
                    { 278, "Bulboaca", 5 },
                    { 279, "Caracușenii Noi", 5 },
                    { 280, "Caracușenii Vechi", 5 },
                    { 281, "Chirilovca", 5 },
                    { 282, "Colicauți", 5 },
                    { 283, "Corjeuți", 5 },
                    { 284, "Coteala", 5 },
                    { 285, "Cotiujeni", 5 },
                    { 286, "Criva", 5 },
                    { 287, "Drepcăuți", 5 },
                    { 288, "Grimăncăuți", 5 },
                    { 289, "Grimești", 5 },
                    { 290, "Groznița", 5 },
                    { 291, "Halahora de Jos", 5 },
                    { 292, "Halahora de Sus", 5 },
                    { 293, "Hlina", 5 },
                    { 294, "Larga", 5 },
                    { 295, "Mărcăuți", 5 },
                    { 296, "Mărcăuții Noi", 5 },
                    { 297, "Medveja", 5 },
                    { 298, "Mihăileni", 5 },
                    { 299, "Pavlovca", 5 },
                    { 300, "Pererîta", 5 },
                    { 301, "Șirăuți", 5 },
                    { 302, "Slobozia-Medveja", 5 },
                    { 303, "Slobozia-Șirăuți", 5 },
                    { 304, "Tabani", 5 },
                    { 305, "Tețcani", 5 },
                    { 306, "Trebisăuți", 5 },
                    { 307, "Trestieni", 5 },
                    { 308, "Cahul", 6 },
                    { 309, "Alexanderfeld", 6 },
                    { 310, "Alexandru Ioan Cuza", 6 },
                    { 311, "Andrușul de Jos", 6 },
                    { 312, "Andrușul de Sus", 6 },
                    { 313, "Badicul Moldovenesc", 6 },
                    { 314, "Baurci-Moldoveni", 6 },
                    { 315, "Borceag", 6 },
                    { 316, "Brînza", 6 },
                    { 317, "Bucuria", 6 },
                    { 318, "Burlăceni", 6 },
                    { 319, "Burlacu", 6 },
                    { 320, "Chioselia Mare", 6 },
                    { 321, "Chircani", 6 },
                    { 322, "Cîșlița-Prut", 6 },
                    { 323, "Colibași", 6 },
                    { 324, "Cotihana", 6 },
                    { 325, "Crihana Veche", 6 },
                    { 326, "Cucoara", 6 },
                    { 327, "Doina", 6 },
                    { 328, "Frumușica", 6 },
                    { 329, "Găvănoasa", 6 },
                    { 330, "Giurgiulești", 6 },
                    { 331, "Greceni", 6 },
                    { 332, "Huluboaia", 6 },
                    { 333, "Hutulu", 6 },
                    { 334, "Iasnaia Poleana", 6 },
                    { 335, "Iujnoe", 6 },
                    { 336, "Larga Nouă", 6 },
                    { 337, "Larga Veche", 6 },
                    { 338, "Lebedenco", 6 },
                    { 339, "Lopățica", 6 },
                    { 340, "Lucești", 6 },
                    { 341, "Manta", 6 },
                    { 342, "Moscovei", 6 },
                    { 343, "Nicolaevca", 6 },
                    { 344, "Paicu", 6 },
                    { 345, "Pașcani", 6 },
                    { 346, "Pelinei", 6 },
                    { 347, "Roșu", 6 },
                    { 348, "Rumeantev", 6 },
                    { 349, "Sătuc", 6 },
                    { 350, "Slobozia Mare", 6 },
                    { 351, "Spicoasa", 6 },
                    { 352, "Taraclia de Salcie", 6 },
                    { 353, "Trataul de Salcie", 6 },
                    { 354, "Tătărești", 6 },
                    { 355, "Tretești", 6 },
                    { 356, "Trifeștii Noi", 6 },
                    { 357, "Tudorești", 6 },
                    { 358, "Ursoaia", 6 },
                    { 359, "Vadul lui Isac", 6 },
                    { 360, "Văleni", 6 },
                    { 361, "Vladimirovca", 6 },
                    { 362, "Zîrnești", 6 },
                    { 363, "Călărași", 8 },
                    { 364, "Bahmut", 8 },
                    { 365, "Bahu", 8 },
                    { 366, "Bravicea", 8 },
                    { 367, "Buda", 8 },
                    { 368, "Bularda", 8 },
                    { 369, "Căbăiești", 8 },
                    { 370, "Dereneu", 8 },
                    { 371, "Duma", 8 },
                    { 372, "Frumoasa", 8 },
                    { 373, "Hîrbovăț", 8 },
                    { 374, "Hîrjauca", 8 },
                    { 375, "Hirova", 8 },
                    { 376, "Hoginești", 8 },
                    { 377, "Horodiște", 8 },
                    { 378, "Leordoaia", 8 },
                    { 379, "Meleșeni", 8 },
                    { 380, "Mîndra", 8 },
                    { 381, "Nișcani", 8 },
                    { 382, "Novaci", 8 },
                    { 383, "Onișcani", 8 },
                    { 384, "Oricova", 8 },
                    { 385, "Palanca", 8 },
                    { 386, "Parcani", 8 },
                    { 387, "Păulești", 8 },
                    { 388, "Peticeni", 8 },
                    { 389, "Pîrjolteni", 8 },
                    { 390, "Pitușca", 8 },
                    { 391, "Podul Lung", 8 },
                    { 392, "Răciula", 8 },
                    { 393, "Rădeni", 8 },
                    { 394, "Sadova", 8 },
                    { 395, "Săseni", 8 },
                    { 396, "Schinoasa", 8 },
                    { 397, "Seliștea Nouă", 8 },
                    { 398, "Sipoteni", 8 },
                    { 399, "Sverida", 8 },
                    { 400, "Temeleuți", 8 },
                    { 401, "Țibirica", 8 },
                    { 402, "Tuzara", 8 },
                    { 403, "Ursari", 8 },
                    { 404, "Valcineț", 8 },
                    { 405, "Vărzăreștii Noi", 8 },
                    { 406, "Cantemir", 7 },
                    { 407, "Acui", 7 },
                    { 408, "Alexandrovca", 7 },
                    { 409, "Antonești", 7 },
                    { 410, "Baimaclia", 7 },
                    { 411, "Bobocica", 7 },
                    { 412, "Cania", 7 },
                    { 413, "Capaclia", 7 },
                    { 414, "Chioselia", 7 },
                    { 415, "Cîietu", 7 },
                    { 416, "Ciobalaccia", 7 },
                    { 417, "Cîrpești", 7 },
                    { 418, "Cîșla", 7 },
                    { 419, "Cociulia", 7 },
                    { 420, "Constantinești", 7 },
                    { 421, "Coștangalia", 7 },
                    { 422, "Crăciun", 7 },
                    { 423, "Dimitrova", 7 },
                    { 424, "Enichioi", 7 },
                    { 425, "Flocoasa", 7 },
                    { 426, "Floricica", 7 },
                    { 427, "Ghioltosu", 7 },
                    { 428, "Gotești", 7 },
                    { 429, "Hănăseni", 7 },
                    { 430, "Haragîș", 7 },
                    { 431, "Hîrtop", 7 },
                    { 432, "Iepureni", 7 },
                    { 433, "Lărguța", 7 },
                    { 434, "Leca", 7 },
                    { 435, "Lingura", 7 },
                    { 436, "Pleșeni", 7 },
                    { 437, "Plopi", 7 },
                    { 438, "Popovca", 7 },
                    { 439, "Porumbești", 7 },
                    { 440, "Sadîc", 7 },
                    { 441, "Șamalia", 7 },
                    { 442, "Șofranovca", 7 },
                    { 443, "Stoianovca", 7 },
                    { 444, "Suhat", 7 },
                    { 445, "Taraclia", 7 },
                    { 446, "Țărăncuța", 7 },
                    { 447, "Tartaul", 7 },
                    { 448, "Tătărășeni", 7 },
                    { 449, "Țiganca", 7 },
                    { 450, "Țiganca Nouă", 7 },
                    { 451, "Toceni", 7 },
                    { 452, "Țolica", 7 },
                    { 453, "Victorovca", 7 },
                    { 454, "Vîlcele", 7 },
                    { 455, "Vișniovca", 7 },
                    { 456, "or. Căinari", 9 },
                    { 457, "Căușeni", 9 },
                    { 458, "Baccealia", 9 },
                    { 459, "Baimaclia", 9 },
                    { 460, "Baurci", 9 },
                    { 461, "s. Căinari", 9 },
                    { 462, "Chircăiești", 9 },
                    { 463, "Chircăieștii Noi", 9 },
                    { 464, "Chițcani", 9 },
                    { 465, "Cîrnățeni", 9 },
                    { 466, "Cîrnățenii Noi", 9 },
                    { 467, "Ciuflești", 9 },
                    { 468, "Constantinovca", 9 },
                    { 469, "Copanca", 9 },
                    { 470, "Coșcalia", 9 },
                    { 471, "Cremenciug", 9 },
                    { 472, "Fîrlădeni", 9 },
                    { 473, "Florica", 9 },
                    { 474, "Gîsca", 9 },
                    { 475, "Grădinița", 9 },
                    { 476, "Grigorievca", 9 },
                    { 477, "Hagimus", 9 },
                    { 478, "Leuntea", 9 },
                    { 479, "Marianca de Sus", 9 },
                    { 480, "Merenești", 9 },
                    { 481, "Opaci", 9 },
                    { 482, "Pervomaisc", 9 },
                    { 483, "Plop", 9 },
                    { 484, "Plopi-Știubei", 9 },
                    { 485, "Săiți", 9 },
                    { 486, "Sălcuța", 9 },
                    { 487, "Sălcuța Nouă", 9 },
                    { 488, "Ștefănești", 9 },
                    { 489, "Surchiceni", 9 },
                    { 490, "Tănătari", 9 },
                    { 491, "Tănătarii Noi", 9 },
                    { 492, "Taraclia", 9 },
                    { 493, "Tocuz", 9 },
                    { 494, "Tricolici", 9 },
                    { 495, "Ucrainca", 9 },
                    { 496, "Ursoaia", 9 },
                    { 497, "Ursoaia Nouă", 9 },
                    { 498, "Valea Verde", 9 },
                    { 499, "Zahorna", 9 },
                    { 500, "Zaim", 9 },
                    { 501, "Zviozdocica", 9 },
                    { 502, "Cimișlia", 12 },
                    { 503, "Albina", 12 },
                    { 504, "Artimonovca", 12 },
                    { 505, "Batîr", 12 },
                    { 506, "Bogdanovca Nouă", 12 },
                    { 507, "Bogdanovca Veche", 12 },
                    { 508, "Cenac", 12 },
                    { 509, "Ciucur-Mingir", 12 },
                    { 510, "Codreni", 12 },
                    { 511, "Coștangalia", 12 },
                    { 512, "Dimitrovca", 12 },
                    { 513, "Ecaterinovca", 12 },
                    { 514, "Fetița", 12 },
                    { 515, "Gradiște", 12 },
                    { 516, "Gura Galbenei", 12 },
                    { 517, "Hîrtop", 12 },
                    { 518, "Ialpug", 12 },
                    { 519, "Ialpujeni", 12 },
                    { 520, "Iurievca", 12 },
                    { 521, "Ivanovca Nouă", 12 },
                    { 522, "Javgur", 12 },
                    { 523, "Lipoveni", 12 },
                    { 524, "Marienfeld", 12 },
                    { 525, "Maximeni", 12 },
                    { 526, "Mereni", 12 },
                    { 527, "Mihailovca", 12 },
                    { 528, "Munteni", 12 },
                    { 529, "Porumbrei", 12 },
                    { 530, "Prisaca", 12 },
                    { 531, "Sagaidac", 12 },
                    { 532, "Sagaidacul Nou", 12 },
                    { 533, "Satul Nou", 12 },
                    { 534, "Schinoșica", 12 },
                    { 535, "Selemet", 12 },
                    { 536, "Suric", 12 },
                    { 537, "Topala", 12 },
                    { 538, "Troițcoe", 12 },
                    { 539, "Valea Perjei", 12 },
                    { 540, "Zloți", 12 },
                    { 541, "Criuleni", 13 },
                    { 542, "Bălăbănești", 13 },
                    { 543, "Bălăsești", 13 },
                    { 544, "Bălțata", 13 },
                    { 545, "Bălțata de Sus", 13 },
                    { 546, "Boșcana", 13 },
                    { 547, "Chetroasa", 13 },
                    { 548, "Cimișeni", 13 },
                    { 549, "Ciopleni", 13 },
                    { 550, "Corjova", 13 },
                    { 551, "Coșernița", 13 },
                    { 552, "Cruglic", 13 },
                    { 553, "Dolinnoe", 13 },
                    { 554, "Drăsliceni", 13 },
                    { 555, "Dubăsarii Vechi", 13 },
                    { 556, "Hîrtopul Mare", 13 },
                    { 557, "Hîrtopul Mic", 13 },
                    { 558, "Hrușova", 13 },
                    { 559, "Ișnovăț", 13 },
                    { 560, "Izbiște", 13 },
                    { 561, "Jevreni", 13 },
                    { 562, "Logănești", 13 },
                    { 563, "Măgdăcești", 13 },
                    { 564, "Mălăiești", 13 },
                    { 565, "Mălăieștii Noi", 13 },
                    { 566, "Mardareuca", 13 },
                    { 567, "Mășcăuți", 13 },
                    { 568, "Miclești", 13 },
                    { 569, "Ohrincea", 13 },
                    { 570, "Onițcani", 13 },
                    { 571, "Pașcani", 13 },
                    { 572, "Porumbeni", 13 },
                    { 573, "Răculești", 13 },
                    { 574, "Ratuș", 13 },
                    { 575, "Rîșcova", 13 },
                    { 576, "Sagaidac", 13 },
                    { 577, "Sagaidacul de Sus", 13 },
                    { 578, "Slobozia-Dușca", 13 },
                    { 579, "Stețcani", 13 },
                    { 580, "Valea Coloniței", 13 },
                    { 581, "Valea Satului", 13 },
                    { 582, "Zăicana", 13 },
                    { 583, "Zolonceni", 13 },
                    { 584, "or. Dondușeni", 14 },
                    { 585, "Arionești", 14 },
                    { 586, "Baraboi", 14 },
                    { 587, "Boroseni", 14 },
                    { 588, "Braicău", 14 },
                    { 589, "Briceni", 14 },
                    { 590, "Briceva", 14 },
                    { 591, "Caraiman", 14 },
                    { 592, "Cernoleuca", 14 },
                    { 593, "Climăuți", 14 },
                    { 594, "Codrenii Noi", 14 },
                    { 595, "Corbu", 14 },
                    { 596, "Crișcăuți", 14 },
                    { 597, "s. Dondușeni", 14 },
                    { 598, "Elenovca", 14 },
                    { 599, "Elizavetovca", 14 },
                    { 600, "Frasin", 14 },
                    { 601, "Horodiște", 14 },
                    { 602, "Moșana", 14 },
                    { 603, "Octeabriscoe", 14 },
                    { 604, "Pivniceni", 14 },
                    { 605, "Plop", 14 },
                    { 606, "Pocrovca", 14 },
                    { 607, "Rediul Mare", 14 },
                    { 608, "Scăieni", 14 },
                    { 609, "Sudarca", 14 },
                    { 610, "Țaul", 14 },
                    { 611, "Teleșeuca", 14 },
                    { 612, "Teleșeuca Nouă", 14 },
                    { 613, "Tîrnova", 14 },
                    { 614, "or. Drochia", 15 },
                    { 615, "Antoneuca", 15 },
                    { 616, "Baroncea", 15 },
                    { 617, "Baroncea Nouă", 15 },
                    { 618, "Ceapaevca", 15 },
                    { 619, "Chetrosu", 15 },
                    { 620, "Cotova", 15 },
                    { 621, "Dominteni", 15 },
                    { 622, "s. Drochia", 15 },
                    { 623, "Fîntînița", 15 },
                    { 624, "Ghizdita", 15 },
                    { 625, "Gribova", 15 },
                    { 626, "Hăsnășenii Mari", 15 },
                    { 627, "Hăsnășenii Noi", 15 },
                    { 628, "Holoșnița Nouă", 15 },
                    { 629, "Iliciovca", 15 },
                    { 630, "Lazo", 15 },
                    { 631, "Măcăreuca", 15 },
                    { 632, "Maramonovca", 15 },
                    { 633, "Miciurin", 15 },
                    { 634, "Mîndîc", 15 },
                    { 635, "Moara de Piatră", 15 },
                    { 636, "Nicoreni", 15 },
                    { 637, "Ochiul Alb ", 15 },
                    { 638, "Palanca", 15 },
                    { 639, "Pelinia", 15 },
                    { 640, "Pervomaiscoe", 15 },
                    { 641, "Petreni", 15 },
                    { 642, "Popeștii de Jos", 15 },
                    { 643, "Popeștii de Sus", 15 },
                    { 644, "Popeștii Noi", 15 },
                    { 645, "Șalvirii Noi", 15 },
                    { 646, "Șalvirii Vechi", 15 },
                    { 647, "Sergheuca", 15 },
                    { 648, "Sofia", 15 },
                    { 649, "Șuri", 15 },
                    { 650, "Șurii Noi", 15 },
                    { 651, "Țarigrad", 15 },
                    { 652, "Zgurița", 15 },
                    { 653, "Cocieri", 16 },
                    { 654, "Corjova", 16 },
                    { 655, "Coșnița", 16 },
                    { 656, "Doroțcaia", 16 },
                    { 657, "Holercani", 16 },
                    { 658, "Mahala", 16 },
                    { 659, "Mărcăuți", 16 },
                    { 660, "Molovata", 16 },
                    { 661, "Molovata Nouă", 16 },
                    { 662, "Oxentea", 16 },
                    { 663, "Pîrîta", 16 },
                    { 664, "Pohrebea", 16 },
                    { 665, "Ustia", 16 },
                    { 666, "Vasilievca", 16 },
                    { 667, "Cupcini", 17 },
                    { 668, "Edineț", 17 },
                    { 669, "Alexăndreni", 17 },
                    { 670, "Alexeevca", 17 },
                    { 671, "Bădragii Noi", 17 },
                    { 672, "Bădragii Vechi", 17 },
                    { 673, "Bleșteni", 17 },
                    { 674, "Brătușeni", 17 },
                    { 675, "Brătușenii Noi", 17 },
                    { 676, "Brînzeni", 17 },
                    { 677, "Burlănești", 17 },
                    { 678, "Buzdugeni", 17 },
                    { 679, "Cepeleuți", 17 },
                    { 680, "Chetroșica Nouă", 17 },
                    { 681, "Chetroșica Veche", 17 },
                    { 682, "Chiurt", 17 },
                    { 683, "Clișcăuți", 17 },
                    { 684, "Constantinovca", 17 },
                    { 685, "Corpaci", 17 },
                    { 686, "Cuconeștii Noi", 17 },
                    { 687, "Cuconeștii Vechi", 17 },
                    { 688, "Fetești", 17 },
                    { 689, "Fîntîna Albă", 17 },
                    { 690, "Gașpar", 17 },
                    { 691, "Goleni", 17 },
                    { 692, "Gordinești", 17 },
                    { 693, "Gordineștii Noi", 17 },
                    { 694, "Hancăuți", 17 },
                    { 695, "Hincăuți", 17 },
                    { 696, "Hlinaia", 17 },
                    { 697, "Hlinaia Mică", 17 },
                    { 698, "Iachimeni", 17 },
                    { 699, "Lopatnic", 17 },
                    { 700, "Onești", 17 },
                    { 701, "Parcova", 17 },
                    { 702, "Poiana", 17 },
                    { 703, "Rîngaci", 17 },
                    { 704, "Rotunda", 17 },
                    { 705, "Ruseni", 17 },
                    { 706, "Slobodca", 17 },
                    { 707, "Șofrîncani", 17 },
                    { 708, "Stolniceni", 17 },
                    { 709, "Terebna", 17 },
                    { 710, "Tîrnova", 17 },
                    { 711, "Trinca", 17 },
                    { 712, "Vancicăuți", 17 },
                    { 713, "Viișoara", 17 },
                    { 714, "Volodeni", 17 },
                    { 715, "Zăbriceni", 17 },
                    { 716, "Fălești", 18 },
                    { 717, "Albinețul Nou", 18 },
                    { 718, "Albinețul Vechi", 18 },
                    { 719, "Beleuți", 18 },
                    { 720, "Bocani", 18 },
                    { 721, "Bocșa", 18 },
                    { 722, "Burghelea", 18 },
                    { 723, "Călinești", 18 },
                    { 724, "Călugăr", 18 },
                    { 725, "Catranîc", 18 },
                    { 726, "Chetriș", 18 },
                    { 727, "Chetrișul Nou", 18 },
                    { 728, "Ciolacu Nou", 18 },
                    { 729, "Ciolacu Vechi", 18 },
                    { 730, "Ciuluc", 18 },
                    { 731, "Comarovca", 18 },
                    { 732, "Cuzmenii Vechi", 18 },
                    { 733, "Doltu", 18 },
                    { 734, "Drujineni", 18 },
                    { 735, "Egorovca", 18 },
                    { 736, "Făgădău", 18 },
                    { 737, "Făleștii Noi", 18 },
                    { 738, "Frumușica", 18 },
                    { 739, "Glinjeni", 18 },
                    { 740, "Hiliuți", 18 },
                    { 741, "Hîncești", 18 },
                    { 742, "Hîrtop", 18 },
                    { 743, "Hitrești", 18 },
                    { 744, "Horești", 18 },
                    { 745, "Hrubna Nouă", 18 },
                    { 746, "Ilenuța", 18 },
                    { 747, "Ișcălău", 18 },
                    { 748, "Ivanovca", 18 },
                    { 749, "Izvoare", 18 },
                    { 750, "Logofteni", 18 },
                    { 751, "Lucăceni", 18 },
                    { 752, "Măgura", 18 },
                    { 753, "Măgura Nouă", 18 },
                    { 754, "Măgureanca", 18 },
                    { 755, "Mărăndeni", 18 },
                    { 756, "Moldoveanca", 18 },
                    { 757, "Musteața", 18 },
                    { 758, "Natalievca", 18 },
                    { 759, "Năvîrneț", 18 },
                    { 760, "Nicolaevca", 18 },
                    { 761, "Obreja Nouă", 18 },
                    { 762, "Obreja Veche", 18 },
                    { 763, "Pervomaisc", 18 },
                    { 764, "Pietrosu", 18 },
                    { 765, "Pietrosul Nou", 18 },
                    { 766, "Pînzăreni", 18 },
                    { 767, "Pînzărenii Noi", 18 },
                    { 768, "Pîrlița", 18 },
                    { 769, "Pocrovca", 18 },
                    { 770, "Pompa", 18 },
                    { 771, "Popovca", 18 },
                    { 772, "Pruteni", 18 },
                    { 773, "Răuțel", 18 },
                    { 774, "Răuțelul Nou", 18 },
                    { 775, "Rediul de Jos", 18 },
                    { 776, "Rediul de Sus", 18 },
                    { 777, "Risipeni", 18 },
                    { 778, "Sărata Nouă", 18 },
                    { 779, "Sărata Veche", 18 },
                    { 780, "Scumpia", 18 },
                    { 781, "Socii Noi", 18 },
                    { 782, "Socii Vechi", 18 },
                    { 783, "Șoltoaia", 18 },
                    { 784, "Suvorovca", 18 },
                    { 785, "Țapoc", 18 },
                    { 786, "Taxobeni", 18 },
                    { 787, "Unteni", 18 },
                    { 788, "Valea Rusului", 18 },
                    { 789, "Vrănești", 18 },
                    { 790, "Florești", 19 },
                    { 791, "Ghindești", 19 },
                    { 792, "Mărculești", 19 },
                    { 793, "Alexandrovca", 19 },
                    { 794, "Alexeevca", 19 },
                    { 795, "Antonovca", 19 },
                    { 796, "Băhrinești", 19 },
                    { 797, "Bezeni", 19 },
                    { 798, "Bobulești", 19 },
                    { 799, "Bursuc", 19 },
                    { 800, "Căprești", 19 },
                    { 801, "Cașunca", 19 },
                    { 802, "Cenușa", 19 },
                    { 803, "Cernița", 19 },
                    { 804, "Chirilovca", 19 },
                    { 805, "Ciripcău", 19 },
                    { 806, "Ciutulești", 19 },
                    { 807, "Coșernița", 19 },
                    { 808, "Cuhureștii de Jos", 19 },
                    { 809, "Cuhureștii de Sus", 19 },
                    { 810, "Cunicea", 19 },
                    { 811, "Domulgeni", 19 },
                    { 812, "Dumitreni", 19 },
                    { 813, "Făgădău", 19 },
                    { 814, "Frumușica", 19 },
                    { 815, "Frumușica Nouă", 19 },
                    { 816, "Frunzești", 19 },
                    { 817, "Ghindești", 19 },
                    { 818, "Gura Căinarului", 19 },
                    { 819, "Gura Camencii", 19 },
                    { 820, "Gvozdova", 19 },
                    { 821, "Hîrtop", 19 },
                    { 822, "Iliciovca", 19 },
                    { 823, "Ion Vodă", 19 },
                    { 824, "Ivanovca", 19 },
                    { 825, "Izvoare", 19 },
                    { 826, "Japca", 19 },
                    { 827, "Lunga", 19 },
                    { 828, "Maiscoe", 19 },
                    { 829, "Mărculești", 19 },
                    { 830, "Mărinești", 19 },
                    { 831, "Mihailovca", 19 },
                    { 832, "Năpadova", 19 },
                    { 833, "Nicolaevca", 19 },
                    { 834, "Octeabriscoe", 19 },
                    { 835, "Prajila", 19 },
                    { 836, "Prodănești", 19 },
                    { 837, "Prodăneștii Vechi", 19 },
                    { 838, "Putinești", 19 },
                    { 839, "Rădulenii Noi", 19 },
                    { 840, "Rădulenii Vechi", 19 },
                    { 841, "Roșietici", 19 },
                    { 842, "Roșieticii Vechi", 19 },
                    { 843, "Sănătăuca", 19 },
                    { 844, "Scăieni", 19 },
                    { 845, "Sevirova", 19 },
                    { 846, "Sîrbești", 19 },
                    { 847, "Ștefănești", 19 },
                    { 848, "Stîrceni", 19 },
                    { 849, "Temeleuți", 19 },
                    { 850, "Țipordei", 19 },
                    { 851, "Țîra", 19 },
                    { 852, "Tîrgul-Vertiujeni", 19 },
                    { 853, "Trifănești", 19 },
                    { 854, "Unchitești", 19 },
                    { 855, "Valea Rădoaiei", 19 },
                    { 856, "Vărvăreuca", 19 },
                    { 857, "Văscăuți", 19 },
                    { 858, "Vertiujeni", 19 },
                    { 859, "Zăluceni", 19 },
                    { 860, "Zarojeni", 19 },
                    { 861, "Glodeni", 20 },
                    { 862, "Balatina", 20 },
                    { 863, "Bisericani", 20 },
                    { 864, "Brînzeni", 20 },
                    { 865, "Butești", 20 },
                    { 866, "Cajba", 20 },
                    { 867, "Camenca", 20 },
                    { 868, "Camencuța", 20 },
                    { 869, "Ciuciulea", 20 },
                    { 870, "Clococenii Vechi", 20 },
                    { 871, "Cobani", 20 },
                    { 872, "Cot", 20 },
                    { 873, "Cuhnești", 20 },
                    { 874, "Danu", 20 },
                    { 875, "Dușmani", 20 },
                    { 876, "Fundurii Noi", 20 },
                    { 877, "Fundurii Vechi", 20 },
                    { 878, "Hîjdieni", 20 },
                    { 879, "Iabloana", 20 },
                    { 880, "Limbenii Noi", 20 },
                    { 881, "Limbenii Vechi", 20 },
                    { 882, "Lipovăț", 20 },
                    { 883, "Moara Domnească", 20 },
                    { 884, "Molești", 20 },
                    { 885, "Movileni", 20 },
                    { 886, "Nicolaevca", 20 },
                    { 887, "Petrunea", 20 },
                    { 888, "Serghieni", 20 },
                    { 889, "Soroca", 20 },
                    { 890, "Stîrcea", 20 },
                    { 891, "Sturzovca", 20 },
                    { 892, "Tomeștii Noi", 20 },
                    { 893, "Tomeștii Vechi", 20 },
                    { 894, "Ustia", 20 },
                    { 895, "Viișoara", 20 },
                    { 896, "Hîncești", 21 },
                    { 897, "Anini", 21 },
                    { 898, "Bălceana", 21 },
                    { 899, "Bobeica", 21 },
                    { 900, "Boghiceni", 21 },
                    { 901, "Bozieni", 21 },
                    { 902, "Brătianovca", 21 },
                    { 903, "Bujor", 21 },
                    { 904, "Buțeni", 21 },
                    { 905, "Călmățui", 21 },
                    { 906, "Caracui", 21 },
                    { 907, "Cărpineanca", 21 },
                    { 908, "Cărpineni", 21 },
                    { 909, "Cățeleni", 21 },
                    { 910, "Chetroșeni", 21 },
                    { 911, "Cioara", 21 },
                    { 912, "Ciuciuleni", 21 },
                    { 913, "Cornești", 21 },
                    { 914, "Coroliovca", 21 },
                    { 915, "Costești", 21 },
                    { 916, "Cotul Morii", 21 },
                    { 917, "Crasnoarmeiscoe", 21 },
                    { 918, "Dahnovici", 21 },
                    { 919, "Dancu", 21 },
                    { 920, "Drăgușeni", 21 },
                    { 921, "Drăgușenii Noi", 21 },
                    { 922, "Dubovca", 21 },
                    { 923, "Feteasca", 21 },
                    { 924, "Fîrlădeni", 21 },
                    { 925, "Frasin", 21 },
                    { 926, "Fundul Galbenei", 21 },
                    { 927, "Horjești", 21 },
                    { 928, "Horodca", 21 },
                    { 929, "Ivanovca", 21 },
                    { 930, "Lăpușna", 21 },
                    { 931, "Leușeni", 21 },
                    { 932, "Logănești", 21 },
                    { 933, "Marchet", 21 },
                    { 934, "Mereșeni", 21 },
                    { 935, "Mingir", 21 },
                    { 936, "Mirești", 21 },
                    { 937, "Negrea", 21 },
                    { 938, "Nemțeni", 21 },
                    { 939, "Obileni", 21 },
                    { 940, "Onești", 21 },
                    { 941, "Pașcani", 21 },
                    { 942, "Pereni", 21 },
                    { 943, "Pervomaiscoie", 21 },
                    { 944, "Pogănești", 21 },
                    { 945, "Rusca", 21 },
                    { 946, "Sărata-Galbenă", 21 },
                    { 947, "Sărata-Mereșeni", 21 },
                    { 948, "Sărăteni", 21 },
                    { 949, "Secăreni", 21 },
                    { 950, "Secărenii Noi", 21 },
                    { 951, "Semionovca", 21 },
                    { 952, "Șipoteni", 21 },
                    { 953, "Sofia", 21 },
                    { 954, "Stolniceni", 21 },
                    { 955, "Strîmbeni", 21 },
                    { 956, "Tălăiești", 21 },
                    { 957, "Valea Florii", 21 },
                    { 958, "Voinescu", 21 }
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("TRUNCATE TABLE Locations");
        }
    }
}
